format: service/1
service: workflow
sdk:
  repository: https://github.com/beyond10x/service-sdk.git
  revision: 3ac9f30a5e49015d2c61d6ca292c8889f90403c4
semantic:
  root: spec/workflow
  sources:
    - system.yaml
    - components.yaml
    - domains/definition.yaml
runtime: service/runtime.yaml
scenarios:
  - service/scenarios/workflow.yaml
release:
  generated_root: generated
  image_repository: ghcr.io/beyond10x/workflow
  version: 0.3.5
  build_base:
    repository: docker.io/library/rust
    digest: sha256:8fa55b2f3ddf97471ab6a767bfa3f37e6bad0986ba823e75fea57e2a2a5c3073
  runtime_base:
    repository: gcr.io/distroless/cc-debian12
    digest: sha256:e5d81ddde149641e2a9ba55be4545bc125c67de07508b03ba4c22e6eb0ded5aa
  storage_size: 1Gi
